### ISSUE TITLE
Source filenames, project structure

### ISSUE THREAD

**Issue by farwayer** [status-im/react-native-desktop#104]
What if we rename source files to be CamelCase, remove react prefix (useless) and move classes to `react::`, `reactnative::` (`react_native::`) or `rn::` namespace? Filenames are long and unreadable now.

It will be nice to have good project structure also. As done for Android and iOS layers. It is too many files for one dir already.

For example `ImageManager` class inside `reactnative::` namespace in `views/ImageManager.{h,cpp}`. It will help to keep code more clean, simple and supportable.

I can help with this changes.

**Comment by vkjr** [comment]
`ComponentManagers` folder created for better structure.
