### ISSUE TITLE
UIManager.RCTScrollView.Commands is undefined

### ISSUE THREAD

**Issue by loopingrage** [status-im/react-native-desktop#134]
I can see that `scrollTo` is implemented in [scrollviewmanager.cpp](https://github.com/status-im/react-native-desktop/blob/react-native-qt/ReactQt/runtime/src/componentmanagers/scrollviewmanager.cpp#L32) but attempting to invoke it from the JavaScript side fails with:

```
Cannot read property 'scrollTo' of undefined
```

The issue seems to be that `UIManager.RCTScrollView.Commands` is undefined in [ScrollResponder.js](https://github.com/status-im/react-native-desktop/blob/react-native-qt/Libraries/Components/ScrollResponder.js#L416). It appears that this command is not being properly registered with the UIManager.

I'm happy to write up a PR if someone can point me in the right direction.

**Comment by MaxRis** [comment]
To be more specific in steps to start from:

1. Define C++ class for RCTScrollView native component in similar general way how it's done for RCTScrollViewManager, but moduleName() method should return RCTScrollView.

2. Register via Bridge new C++ class for RCTScrollView in similar way like it's done for RCTScrollViewManager

3. Update ScrollView.js code to resolve `RCTScrollView` native component, for example, into RCTScrollView. 

`RCTScrollView = requireNativeComponent('RCTScrollView', null);`

4. Investigate usage of RCTScrollView in JS code and implement missed functionality. Also referencing Obj-C implementation of RCTScrollView should help ( react/View/RCTScrollView.m )

**Comment by vkjr** [comment]
@MaxRis, when components registered, they names are derived from manager name, but without "Manager" part, that can be seen in `ComponentData::name()` function. So we have module `RCTButtonViewManager`, but it is used in js side with `var RCTButton = requireNativeComponent('RCTButtonView', Button);`
Same for ScrollView, when we require `RCTScrollView`, that should result in adressing `RCTScrollViewManager` in cpp code. So I think we don't need additional C++ class.

@loopingrage ,
Didn't investigate fully, but probably the reason of issue can be found in `UIManager.js`. In line 60 you can see that 'Commands' property registered additionally for ios native components. But not for ubuntu. I suspect that this part of code should be copied for ubuntu components.
This is just an assumption, need to be investigated.

**Comment by MaxRis** [comment]
@vkjr great! thanks
So, seems, JS side should be adjusted mostly

**Comment by vkjr** [comment]
Tested the issue, scrollTo() works fine now.
Closing.
