### ISSUE TITLE
Custom Modules

### ISSUE THREAD

**Issue by loopingrage** [status-im/react-native-desktop#139]
Hey there,

I can see in [bridge.cpp](https://github.com/status-im/react-native-desktop/blob/react-native-qt/ReactQt/runtime/src/bridge.cpp#L343) where the internal modules are registered and initialized. What I can't figure out if how our application can programmatically register custom modules. Is there an example of how to do that somewhere?

**Comment by MaxRis** [comment]
Hi @loopingrage ,

Do you mean custom node modules installed in node_modules folder? If yes, then it can't at the moment, but we have https://github.com/status-im/react-native-desktop/issues/131 that should be implemented pretty soon.

**Comment by loopingrage** [comment]
Hey @MaxRis. No, I mean custom native modules that the QT App wants to make available to the JS side similar to the core modules like DeviceInfo, Networking, etc. We can obviously fork this repo and add our model to `internalModules` [here](https://github.com/status-im/react-native-desktop/blob/react-native-qt/ReactQt/runtime/src/bridge.cpp#L77) but we figured there has to be some better way that doesn't require modifying the runtime code.

**Comment by MaxRis** [comment]
Hey @loopingrage , thank you for the explanation!
This sounds like pretty important feature and possible it still might be implemented in scope of #131 issue.
It seems if we talk regarding any custom modules (from node_modules or not), framework should provide some kind of API to register 3rd party modules.

**Comment by MaxRis** [comment]
Hi @loopingrage I'm supposing to start looking into this. Will update you once will have some working changes. Thanks

**Comment by MaxRis** [comment]
Hey @loopingrage , here it's [PR](https://github.com/status-im/react-native-desktop/pull/147) to address initial support of custom native modules

**Comment by MaxRis** [comment]
Closing with merged https://github.com/status-im/react-native-desktop/pull/147
