### ISSUE TITLE
(Documentation, support) Is it cross platform?

### ISSUE THREAD

**Issue by lil5** [status-im/react-native-desktop#141]
I really like the looks of this project.  

I can't see the documentation or mention of support for Mac or Windows but I am seeing lots of Mac related pull requests.

1. Have I missed the documentation? 
1. Is/will this project cross platform (Linux, Mac, Windows)?
1. If so how can I build for those platforms?

**Comment by MaxRis** [comment]
Hello @lil5 ,

1. "Work in Progress" to start official support of Mac OS. But you should be able to build and run apps with similar way how it's done on Ubuntu ( https://github.com/status-im/react-native-desktop/blob/react-native-qt/README-ubuntu.md https://github.com/status-im/react-native-desktop/blob/react-native-qt/Development-linux.md )
2. Yes
3. I guess, the best option if you will start from Ubuntu and after you will get success there, you can repro similar steps on Mac or Windows. We haven't tried to build sources on Windows yet. But Mac should work.

**Comment by lil5** [comment]
Thanks for the answer
