### ISSUE TITLE
Better instruction how to start a new application

### ISSUE THREAD

**Issue by Dohxis** [status-im/react-native-desktop#145]
Hello, 

I would like to say that you are doing a really great job on this repository. The only suggestion I have is a better tutorial how to actually start using the library. There are lots of steps involved, which can go wrong. I am stuck on getting everything setuped right now and I think a better documentation would really help.

Is there a way to somehow help writing better documentation?  Would love to discuss it.

**Comment by andytudhope** [comment]
Hey @Dohxis! Thanks for opening this - I totally agree. I'm gonna ping the team about this, make sure they get back to you, and then maybe - with a little direction - you could help put some docs together with me? A video would be particularly awesome if the team is able to get you set up correctly 😉 You can also always log in to our open source wiki and edit yourself where you see fit: wiki.status.im and join us in chat.status.im for anything else!

**Comment by MaxRis** [comment]
Hi @Dohxis ,

We can send invitation to your email to join contributors` Riot's chat.
After recent merge with origin react-native v. 0.50 creation of apps is broken, but should be resolved with available PR.
Just after that I will try to revise documentation to simplify it significantly.

Thanks!

**Comment by vkjr** [comment]
@Dohxis, documentation was extended - https://github.com/status-im/react-native-desktop#getting-started
Please try :) If you'll have problems with starting and running a project, please add a new issue. We will answer and extend docs accordingly.
Closing this one for now.
