### ISSUE TITLE
react-native-linear-gradient support 

### ISSUE THREAD

**Issue by MaxRis** [status-im/react-native-desktop#169]
Origin repository URL https://github.com/react-native-community/react-native-linear-gradient

**Comment by vkjr** [comment]
@MaxRis, you made implementation here - https://github.com/status-im/react-native-linear-gradient/tree/desktop-platform-v230
Can we close the issue?

**Comment by MaxRis** [comment]
Probably, we can close (going to do that), but it was "minimal" implementation to pass compilation and avoid runtime failures. We can open new issues for missed functionality.
