### ISSUE TITLE
Linux Qt port of critical react-native modules required

### ISSUE THREAD

**Issue by MaxRis** [status-im/react-native-desktop#17]
Critical modules to be ported:

1. react-native-status
2. react-native-webview-bridge
3. realm
4. react-native-i18n

For update info please check link:
https://github.com/status-im/status-react/wiki/react-native-modules

**Comment by vkjr** [comment]
@MaxRis, can we close this now?

**Comment by MaxRis** [comment]
Hopefully, yes :)

**Comment by vkjr** [comment]
Cool :)
