### ISSUE TITLE
transform does not work

### ISSUE THREAD

**Issue by ndpmurphy** [status-im/react-native-desktop#196]
In the examples directory the Image example does a transpose of a png. The image is the word google. If you run it on IOS then the word google appears once and is disappearing into the distance with a 'perspective' and rotation applied as a transpose.

On Ubuntu if I run the same example I see several copies of the bitmap with no rotation or perspective applied. 

I expected this to work since there was a commit from  @justincan  back in 2016 to implement transform. It was commit 0e25614c1dc023b935221abf12d7aba919ba583f. Maybe something broke it afterwards.

### Is this a bug report?
Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?
YES

### Environment
Scanning folders for symlinks in /home/osboxes/AwesomeProject/node_modules (19ms)

Environment:
  OS: Linux 4.13
  Node: 8.9.4
  Yarn: Not Found
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: Not Found

I am not sure why it says react-native not found - I assume it is because react native is not in package.json because I am at the root of the react-native  repo. Git hash  058c0f424fcc38029b8e6cbd82907779edc0e6d6 on branch  react-native-qt

### Steps to Reproduce
1. Install the status-im/react-native-desktop repo
2. Build the QT project
3. Run the image example

### Expected Behavior

I expect to see the word google with perspective and rotation applied ( as per IOS)
![image](https://user-images.githubusercontent.com/5898278/36143344-bfb6a33a-10a2-11e8-850a-36b49c2c4cda.png)

### Actual Behavior

See attached screenshot, of Google png ppearing multiple times
![image](https://user-images.githubusercontent.com/5898278/36143292-9f325ca8-10a2-11e8-936f-1bb73d558889.png)

I also reproduced this problem in one of my own programs where I tried to apply a transform with translateX to a view. It was a simpler case than the ImageApp example, but it also failed. In that case the view simply stayed where the layout engine put it, but the transform was  ignored. Again, onIOS it worked fine.

**Comment by ndpmurphy** [comment]
@vkjr The is a commit from 2016 that says it implemented transform, but the code has changed a lot since then. In commit 57872b8aafc5244097008c6d324f2c106f3fa236 you made changes that look like they removed some of the code that had previously implemented the transform. After your commit the MatrixTransform in viewmanager.cpp is no longer used.

I am trying to run older versions to confirm if transform did work and when it stopped working, but unfortunatly the older versions crash for me on unrelated issues.

**Comment by vkjr** [comment]
@ndpmurphy, thanks for reporting this! Yes, I was removing transform one day, we had an issues with that feature. Now it doesn't work and it would be nice to return it back. We will fix that issue when have time.

**Comment by ndpmurphy** [comment]
A fix for transform this has been submitted as https://github.com/status-im/react-native-desktop/pull/202

**Comment by vkjr** [comment]
@ndpmurphy, please check my comment on pull-request, thanks.

**Comment by ndpmurphy** [comment]
Apologies that the first pull request was a mess  - I used the wrong branch. There is now a more sensible pull request at https://github.com/status-im/react-native-desktop/pull/203

**Comment by vkjr** [comment]
@ndpmurphy, thanks I'll review it soon.

**Comment by vkjr** [comment]
@ndpmurphy, added comments to your PR. Please address them and I'll merge it.
Thank you!
