### ISSUE TITLE
Cross Compiling to ARM

### ISSUE THREAD

**Issue by qrpike** [status-im/react-native-desktop#231]
I just have a simple question if this would be possible to compile onto a ARMv5 machine? V8/Nodejs will not run on armv5, so I was curious if this compiles to something, or still runs in the node/v8 vm?

Thanks,

**Comment by MaxRis** [comment]
Hey @qrpike , there is [PR](https://github.com/status-im/react-native-desktop/pull/216) to build and support embedded JavaScriptCore optionally instead of Node.JS. PR makes it available for Linux users so far.
It seems should exists the way to build JavaScriptCore for ARM.
P.S. JavaScriptCore support is not yet well tested and there exist issues with it. Thanks

**Comment by arnetheduck** [comment]
@qrpike Out of curiosity, where do you find ARMv5's these days?

**Comment by qrpike** [comment]
@arnetheduck Not by choice lol A project I'm working on @ a large beverage company.

@MaxRis Is the PR working? I pretty much just need to compile something and check the general performance. If it works, then we can put resources onto the project - and hopefully contribute to the project.

**Comment by arnetheduck** [comment]
@qrpike ok cool - was just curious what kind of device it might be - was having a discussion the other day where Ethereum could and couldn't run in the future ;)

**Comment by MaxRis** [comment]
@qrpike with this PR I was able to run RNTesterApp.desktop.js ( react-native's JS app to browse available react-native components usage JS samples ) and even run StatusIm sources ( https://github.com/status-im/status-electron/tree/master-react-native-qt ). But again, current PR tested only on Linux (it also automatically builds JavaScriptCore libraries from general CMake build scripts), that's the first try to integrate original react-native's C++ wrapper around JavaScriptCore into react-native-desktop project (not everything works and implemented as expected). This PR should be good starting point if someone looking to integrate some custom JS engine into react-native-desktop.
