### ISSUE TITLE
TextInput issues

### ISSUE THREAD

**Issue by siphiuel** [status-im/react-native-desktop#255]
Below is a sample code that allows to reproduce a problem:
```js
import React, {Component} from 'react';
import { AppRegistry, Modal, Text, TextInput, View, TouchableHighlight } from 'react-native';
import {
  Menu,
  MenuProvider,
  MenuOptions,
  MenuOption
} from 'react-native-popup-menu';
import MenuTrigger from 'react-native-popup-menu';
class rn_list extends Component {
  render () {
    return (
      <View>
      <Text>lots of text</Text>
           <TextInput placeholder='some text' style={{backgroundColor: '#00ff00', fontSize: 20}}/>
      </View>
);
  }
}

AppRegistry.registerComponent('rn_list', () => rn_list);
```

There are 3 issues visible, as compared to running in iOS Simulator:
1. Background color setting is ignored.
2. Font size setting is ignored.
3. TextInput component is shifted to the right.

**Comment by vkjr** [comment]
@siphiuel, points 1 and 2 from this issue will be fixed now.
As for 3rd one, "TextInput component is shifted to the right.", it is not fully correct. TextInput component placed as it needs to be, but the text has left margin (qt sets this margin in style for mac platform). You can check it by setting `borderWidth=1` in TextInput style.
<img width="338" alt="screen shot 2018-06-17 at 4 27 41 pm" src="https://user-images.githubusercontent.com/5786310/41508328-a2c04dca-724b-11e8-914e-ffb2558a36d8.png">

**Comment by siphiuel** [comment]
@vkjr thanks for clarification on #3. I've only compared with iOS simulator, did not know about macOS styling rules that apply here.

**Comment by vkjr** [comment]
Just to clarify - those are styling of Qt for macOS and I'm not sure how they are aligned with macOS design guidelines :) But they look quite reasonable. We rarely have editboxes on desktop without margin.

**Comment by vkjr** [comment]
Closing this one if you don't mind :)
