### ISSUE TITLE
Cannot quickly switch between chats (TouchableHighlight is working slowly)

### ISSUE THREAD

**Issue by churik** [status-im/react-native-desktop#288]
### Is this a bug report?

Yes

### Environment
MacBook Pro (Retina, 15-inch, Mid 2015)
*OS:* Mac OSx High Sierra 10.13.5
*Build:* Status version: desktop build 10/07/18 (after merge https://github.com/status-im/status-react/pull/4752)

### Steps to Reproduce

1. Open status-desktop
2. Sign Up
3. Join to several public channels
4. Switching between them

### Expected Behavior
I can switch between chats

### Actual Behavior
I cannot switch between chats or switching is working extremely slowly

### Logs
* Video: http://take.ms/g1qNC
* Log: [StatusIm.txt](https://github.com/status-im/react-native-desktop/files/2179254/StatusIm.txt)

**Comment by vkjr** [comment]
@churik, you added this bug to `react-native-desktop` repository, but it is related to `status-react`.

**Comment by churik** [comment]
Closed, corresponding https://github.com/status-im/status-react/issues/5112 is created
