### ISSUE TITLE
 Public chat name is cut when it is selected

### ISSUE THREAD

**Issue by churik** [status-im/react-native-desktop#289]
### Is this a bug report?

Yes

### Environment
MacBook Pro (Retina, 15-inch, Mid 2015)
*OS:* Mac OSx High Sierra 10.13.5
*Build:* Status version: desktop build 10/07/18 (after merge https://github.com/status-im/status-react/pull/4752)

### Steps to Reproduce

- Open Status
- Sign Up
- Join to any public chat (i.e. `#ethereum`)
- Click on it, pay attention to chat name

### Expected Behavior
Can see full name if it is not overlapped with time (i. e. `#ethereum`)

### Actual Behavior
 last character is cut
https://monosnap.com/file/urIlw2eNPzWrXuWZCbuIPbtbkLRg2b)
![wrchatname](https://user-images.githubusercontent.com/4557972/42221090-92ef89d4-7ed9-11e8-99f5-2a546995a681.png)

### Logs
* Video:  [video]( https://monosnap.com/file/urIlw2eNPzWrXuWZCbuIPbtbkLRg2b)

**Comment by vkjr** [comment]
@churik, you added this bug to `react-native-desktop` repository, but it is related to `status-react`.

**Comment by churik** [comment]
Created corresponding https://github.com/status-im/status-react/issues/5113
