### ISSUE TITLE
Use global react-native-cli directly

### ISSUE THREAD

**Issue by madhavarshney** [status-im/react-native-desktop#291]
@MaxRis @vkjr - Today I discovered that you don't need to use the custom cli of `react-native-desktop` to create a new project and you can directly use the stock `react-native-cli` and specify the version of react-native to use instead.  The commands to create a new project would be:

```
npm install --global react-native-cli
react-native init RNDesktopTest --version status-im/react-native-desktop
cd RNDesktopTest
react-native desktop
```

I can submit a PR to add this method to the docs and remove the other one, as this is somewhat easier, removing the need of cloning the whole `react-native-desktop` repository.

**Comment by MaxRis** [comment]
@madhavarshney nice finding! Docs update sounds great!
