### ISSUE TITLE
Some Network requests (depending on the URL) are not returning a body

### ISSUE THREAD

**Issue by pmcxs** [status-im/react-native-desktop#296]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.11.2
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: github:status-im/react-native-desktop => 0.55.4

  Target Platform: Mac

### Steps to Reproduce

Basic page that simply issues a fetch request to a publicly accessible json file and displays the response inline.

#### Working example (ie, no BUG)

1. Follow the steps to create a new app: (https://github.com/status-im/react-native-desktop/blob/master/docs/CreateNewApp.md)
2. Update index.desktop.js with the following content

```
import React from 'react';
import { AppRegistry, ActivityIndicator, Text, View  } from 'react-native';

export default class DesktopSampleApp extends React.Component {

  constructor(props){
    super(props);
    this.state ={ isLoading: true}
  }

  componentDidMount(){

    return fetch('http://facebook.github.io/react-native/movies.json')
      .then((response) => {
        console.log(response.status);
        console.log(response);
        return response.text();
      })
      .then((responseText) => {
        this.setState({
          isLoading: false,
          dataSource: responseText,
        }, function(){});

      })
      .catch((error) =>{
        console.error(error);
      });
  }

  render(){
    if(this.state.isLoading){
      return(
        <View>
          <ActivityIndicator size="large" />
        </View>
      )
    }

    return(
      <View>
        <Text>
          {this.state.dataSource}
        </Text>
      </View>
    );
  }
}

AppRegistry.registerComponent('DesktopSampleApp', () => DesktopSampleApp);
```
3. Execute `run-native run-desktop`

The app will show the following result:

![image](https://user-images.githubusercontent.com/1152094/42952079-8eae0a56-8b6f-11e8-8552-031c7906925e.png)

#### Non-working example (bug happens)
4. Replace the fetch url with: http://www.json-generator.com/api/json/get/ceQAbxMTkO  (this URL actually returns a very similar JSON to the working example)

5. Execute `run-native run-desktop`

The app will appear blank. 

### Expected Behavior

The response should be displayed on the screen

### Actual Behavior

Although the response is a 200, the body comes out empty for some URLs (validated it on the Remote JS debugging, as I'm logging the full response)

I did validate a couple of variants to diagnose the problem, without success:

- Content Type: Tried different ones to make sure this wasn't a JSON parse problem
- HTTP vs HTTPS: Tried counterparts of the various URLs and it didn't affect the outcome.
- Content Length: Also no effect
- The actual content: I've created a local Node proxy that returned the exact same JSON as one of the URLs that works, and it also didn't work. Thus, it's not related with the actual content.
- Using Fetch vs XHR: had the same result

### Reproducible Demo

See Above in "Steps to Reproduce"

**Comment by MaxRis** [comment]
Hey @pmcxs , thank you for the detailed report with samples, will take a look, thanks

**Comment by vkjr** [comment]
@pmcxs, `fetch()` fixed now. Checked the link you provided. It works fine.
Closing the issue.
