### ISSUE TITLE
Selective logging in react-native-desktop

### ISSUE THREAD

**Issue by vkjr** [status-im/react-native-desktop#329]
Currently `react-native-desktop` produces quite a lot of log output to console.
I'd be happy if we have some configuration file where logging can be tweaked, something like:

```
LOG_FLEX=TRUE
LOG_NETWORK=FALSE
LOG_STATUSGO=FALSE
LOG_BRIDGE_EVENTS=TRUE
```

That would make reading logs more convenient

**Comment by MaxRis** [comment]
It would be nice to have possibility to turn on/off logging on runtime similar like status-go logging level can be configured from .env config file (and keep config values in the same .env file).
Some kind of propagation from CLJS to every native module is required in this case.

**Comment by vkjr** [comment]
I was thinking about possibility to tweak logging within `react-native-desktop`, without cljs involved. This feature will be useful not only for `status-react` but for any other project.

For example we can have kind of log_settings.ini file with. When log statement invoked, it can check if this particular type of logging enabled or not. That allows runtime configuration.
Also within react-native code we can add some function like "registerLogging("LOG_FLEX"), which will add new record to `log_settings.ini` file. 
It can be accessible via `ModuleInterface` to allow 3rd party modules like `react-native-status` add their own logging options.

In `status-react` we can add some way to modify what log settings file and changes will be automatically picked up by running modules.

**Comment by MaxRis** [comment]
Sounds good!
