### ISSUE TITLE
TextInput component issues

### ISSUE THREAD

**Issue by siphiuel** [status-im/react-native-desktop#332]
There are some issues with `TextInput` component:
1. `defaultValue` property is missing.
2. `value` property makes the component non-editable. Additionally, missing `height` and `width` properties make the component non-clickable. The behavior can be seen when running the following code sample:
```js
import React, {Component} from 'react';
import { AppRegistry, TextInput, Modal, Text, View, TouchableHighlight } from 'react-native';
class rn_test extends Component {
    render () {
          return (
                  <View style={{backgroundColor: 'rgba(0,0,0,0.4)'}}>
                    <Text>some text</Text>
                    <TextInput value={'default value'}
            style={{top: 20, width: 100, height: 30, backgroundColor: 'rgba(0,0,0,0.1)'}}/>
                  </View>
          );
        }
}

AppRegistry.registerComponent('rn_test', () => rn_test);
```
Clicking on the component and typing will have no effect (`default value` will still be visible). Also, component will not be clickable unless `width` and `height` are set.

**Comment by vkjr** [comment]
@siphiuel, could you please provide some js code that shows the problem. I was checking 'value' property few weeks ago and I'm pretty sure it exists and works :)

**Comment by siphiuel** [comment]
@vkjr Yes, agree, sorry for trouble! (https://github.com/status-im/status-react/pull/5789#discussion_r216352726). Will edit it to leave `defaultValue`reference only.

**Comment by vkjr** [comment]
@siphiuel, it looks from documentation and source code that `value` property is intentionally implemented to make `TextInput` non-editable after it is set. `value` specifies content that shouldn't be changed at all.
Excerpt from a doc:
```
The value to show for the text input. TextInput is a controlled component, which means the native value will be forced to match this value prop if provided. For most uses, this works great, but in some cases this may cause flickering - one common cause is preventing edits by keeping value the same.```
From here: https://facebook.github.io/react-native/docs/textinput#value

**Comment by siphiuel** [comment]
@vkjr In the above doc excerpt, `preventing edits by keeping value the same` is a description of a possible technique to use, not a component limitation. I've tested it inside iOS simulator, it works fine even after `value` is set.

**Comment by siphiuel** [comment]
This whole `defaultValue` vs `value` business is confusing indeed...

**Comment by vkjr** [comment]
Yep, totally agree :) Will play around with properties

**Comment by vkjr** [comment]
@siphiuel, could you please check this issue? I believe TextInput is fixed now.
When you set `defaultValue` - it is visible and editable
When you set `value` - it is non-editable until you change it from state, like this (from react-native docs):
```javascript
import React, { Component } from 'react';
import { AppRegistry, TextInput } from 'react-native';

export default class UselessTextInput extends Component {
  constructor(props) {
    super(props);
    this.state = { text: 'Useless Placeholder' };
  }

  render() {
    return (
      <TextInput
        style={{height: 40, borderColor: 'gray', borderWidth: 1}}
        onChangeText={(text) => this.setState({text})}
        value={this.state.text}
      />
    );
  }
}
```
