### ISSUE TITLE
Incorrect position of button in Alert

### ISSUE THREAD

**Issue by vkjr** [status-im/react-native-desktop#362]
Example code: 
```
        <TouchableHighlight onPress={()=> Alert.alert('Highlight pressed')} >
          <Text>
            Click here
          </Text>
        </TouchableHighlight>
```

Result:  
<img width="643" alt="screen shot 2018-10-05 at 6 18 11 pm" src="https://user-images.githubusercontent.com/5786310/46544039-2802f980-c8cb-11e8-9702-561b439cb5a6.png">

**Comment by chadyj** [comment]
I'm not seeing the weird button anymore.  Still an issue?

<img width="304" alt="screen shot 2018-10-29 at 12 07 25 pm" src="https://user-images.githubusercontent.com/116099/47646302-cd7c5680-db73-11e8-8d55-b27a9ff77747.png">

**Comment by dmitryn** [comment]
Still looks not aligned to me:

<img width="440" alt="screenshot 2018-11-01 11 39 27" src="https://user-images.githubusercontent.com/23836/47847235-dadf4e00-ddca-11e8-8d03-3a07b6da63c9.png">

But looks good with 2 or 3 buttons:

<img width="293" alt="screenshot 2018-11-01 11 39 49" src="https://user-images.githubusercontent.com/23836/47847236-dadf4e00-ddca-11e8-8175-0623c7d69e2d.png">

**Comment by chadyj** [comment]
Back to being broken for me

<img width="394" alt="screen shot 2018-11-01 at 11 45 12 am" src="https://user-images.githubusercontent.com/116099/47847478-a4ee9980-ddcb-11e8-9ff6-715a9e90e001.png">
