### ISSUE TITLE
HTTP Fetch does not work on Linux

### ISSUE THREAD

**Issue by goranjovic** [status-im/react-native-desktop#373]
## Environment
Linux

## Description
HTTP get always returns empty string instead of the content. Found it in the Desktop Wallet PR status-im/status-react#6312 , when getting transaction history from etherscan api didn't work.

## Steps to Reproduce
Try fetching URL contents and check the result 

## Expected Behavior
URL content returned

## Actual Behavior
Empty string is returned instead

**Comment by vkjr** [comment]
@gorangajic, do I understand correctly that you are talking about this fetch functionality - https://facebook.github.io/react-native/docs/network ?

**Comment by goranjovic** [comment]
@vkjr I think so. Whichever one we use in `http/get`

**Comment by goranjovic** [comment]
I think I saw mentions of this issue in relation to "get new version" link not working on Linux

**Comment by vkjr** [comment]
Could you please point to specific invocation in `status-react` that doesn't behave correctly?

**Comment by goranjovic** [comment]
The call started on this line - https://github.com/status-im/status-react/blob/develop/src/status_im/utils/transactions.cljs#L61

It's callback formatter is right above in `format-transactions-response`. By logging response, you can see that it is an empty string.
