### ISSUE TITLE
Remove dependency on hard-coded URL in NetInfo module

### ISSUE THREAD

**Issue by siphiuel** [status-im/react-native-desktop#378]
### Description
Right now, network availability relies on www.google.com to be accessible. It is necessary to devise a way to specify a pool of URLs to use for internet availability checking.

**Comment by vkjr** [comment]
@siphiuel, it would be convenient also to update the description with the usecases where already implemented approach doesn't work fine. If I correctly understand this is, for example, using of `react-native-desktop` app in China, where google is banned.

**Comment by PombeirP** [comment]
Can't we expose the native APIs to our app? E.g. on Android: https://developer.android.com/training/monitoring-device-state/connectivity-monitoring

**Comment by vkjr** [comment]
We used native API but there was a problem. 
https://github.com/status-im/react-native-desktop/pull/339

**Comment by dshulyak** [comment]
What is the rationale behind verification based on some list of URLs?
Application should be "online" if we have enough peers, or if we are also using infura - use some API call of the infura, like 'eth_syncing'. So, to verify that app is online use [admin_peers](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#admin_peers) and ensure that there is atleast one peer with shh protocol, and optionally if there is one peer with les. If les is not used - call locally `eth_syncing`.

**Comment by yenda** [comment]
Can we prioritize this. Privacy is one of the major concerns of our initial user base and this is a serious problem, the call to google domain even includes a unique identifier in the cookies.

**Comment by vkjr** [comment]
@yenda, sure, we can prioritize this. 
@dshulyak, Implementing check the way you suggested should be done on `status-react` side. That won't be related to `react-native-desktop`

**Comment by dshulyak** [comment]
> @dshulyak, Implementing check the way you suggested should be done on status-react side. That won't be related to react-native-deskto

i definitely have nothing against it. does it mean that there is no need for any check in status-native-desktop?

**Comment by siphiuel** [comment]
I think the implementation, as suggested by @MaxRis during offsite, is going to affect both parts (status-react and react-native-desktop). We can only implement it in status-react, but then react-native-desktop will be left with a broken implementation of React Native's NetInfo API. So what is suggested to extend this API in case of Desktop to allow for a list of URLs to check to be provided to the API, like `NetInfo.setURLs(...)` or something. This will be then invoked from status-react once Geth node is initialized and we can get `admin_peers`.

**Comment by vkjr** [comment]
@dshulyak, react-native has `NetInfo.IsConnected` property and it should be properly implemented in `react-native-desktop`, so this issue is totally valid. Checking connection by pinging google probably is not ideal solution :)
But if Status needs to check network by investigating peers, we need to add a new issue in `status-react`

**Comment by siphiuel** [comment]
@vkjr haha, we wrote it simultaneously :)

**Comment by oskarth** [comment]
This appears to be a blocker for desktop release. It isn't clear to me how far away we are from fixing it.

Stepping back, it isn't clear to me that this is a blocker for a desktop release. Can someone please comment?
