### ISSUE TITLE
inverted ListView resizes in the wrong direction

### ISSUE THREAD

**Issue by yenda** [status-im/react-native-desktop#391]
## Description

When a ListView with prop `inverted` `true` is part of a parent view and one of the childs changes in size, the ListView shrinks in the wrong direction. The result is that the content
of the ListView overlaps with the growing view and on the other side there is an empty space

![screenshot from 2018-11-09 15-44-47](https://user-images.githubusercontent.com/1181225/48271596-f71f6280-e43c-11e8-909a-e7dbc7d117c0.png)

Probably related the scroll direction isn't the right either.

**Comment by vkjr** [comment]
@yenda, do you mean ListView or ScrollView. status-react uses ScrollView for chats.
Neither react-native `ScrollView` nor `ListView` support `inverted` property. Only `FlatList` does.

**Comment by vkjr** [comment]
Could you please elaborate on what you are trying to achieve? Providing js code with reproducible problem will help a lot.

**Comment by yenda** [comment]
I replaced it with a flat-list https://github.com/status-im/status-react/pull/6652/files#diff-4435896d687a6a2c9f1061fbe8a32069R173

The problem is that when another element grows (response to another message or simply input field getting bigger as you type a multiline message), the flat-list moves but the content of the flat-list moves the opposite way, which results in the content being "off" as shown in the screenshot

**Comment by vkjr** [comment]
Ok, FlatList.
Btw, how do you find performance with FlatList. I also attempted to use it but at that moment optimized scrollview worked better than FlatList. There were a lot of black spaces in a FlatList during scroll. It wasn't rendering fast enough.

**Comment by yenda** [comment]
well it takes a split second to render messages beyond a certain point when scrolling

**Comment by yenda** [comment]
I think it fixed the problem for inverted flatlist as it was working fine once I managed to open one in the app, but all other flatlists are broken now

**Comment by vkjr** [comment]
Should be fine now - https://github.com/status-im/react-native-desktop/commit/be5617f0824265da4573049627df47b8bf9ffdd5

**Comment by vkjr** [comment]
I'm on mac and list scrolling works the same way as in all other apps, both for inverted and non-inverted list. 
What os do you use?

**Comment by yenda** [comment]
Linux

**Comment by yenda** [comment]
The thing is:
- when not inverted it scrolls in the right direction
- when inverted it scrolls in the wrong direction but click and dragging still scrolls in the right direction

**Comment by vkjr** [comment]
@yenda, `inverted` property in js implemented as a `scaleY=-1` transformation.
In Qt on mac that scaling inverts mouse scroll direction. So to make it back normal I had to add a bit of customization to incoming wheel events. 
I can suppose that Qt behaves differently on mac and linux regarding wheel event.
Could you please try this on Linux:

1) in your project go to `node_modules/react-native/ReactQt/runtime/src/componentmanagers`
2) open `scrollviewmanager.cpp` file
3) find `ScrollViewManager::eventFilter` function and wrap its body in `if defined` pragma (except last `return false` statement.
So the result will look like this:
```cpp
bool ScrollViewManager::eventFilter(QObject* scrollView, QEvent* event) {
#if defined(Q_OS_MACOS)  
  .... //all the code except `return false` is here
#endif
    return false;
}
```
4) Run the app and check that FlatList scrolling works correctly with `inverted` property set to true and false.

If steps above solves your problem, I'll commit this change.
If not - I'll install linux VM and will check it more thoroughly :)
