### ISSUE TITLE
 Duplicate module name: BackAndroid

### ISSUE THREAD

**Issue by lucaszanella** [status-im/react-native-desktop#457]
When I do `npm start` on my newly created project, I get this error:

```
error: bundling failed: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: BackAndroid
  Paths: /home/lz/orwell/orwellJS/node_modules/react-native/Libraries/Utilities/BackAndroid.desktop.js collides with /home/lz/orwell/orwellJS/node_modules/react-native/Libraries/Utilities/BackAndroid.js

This error is caused by a @providesModule declaration with the same name across two different files.
    at setModule (/home/lz/orwell/orwellJS/node_modules/jest-haste-map/build/index.js:462:17)
    at workerReply (/home/lz/orwell/orwellJS/node_modules/jest-haste-map/build/index.js:512:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Loading dependency graph...
 
```
I already tried cleaning everything and reinstalling node_modules but this happens again.

 ```
 React Native Environment Info:
    System:
      OS: Linux 4.13 Ubuntu 17.10 (Artful Aardvark)
      CPU: (4) x64 Intel Core Processor (Broadwell, no TSX)
      Memory: 122.68 MB / 3.85 GB
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 10.15.1 - ~/Downloads/node-v10.15.1-linux-x64/bin/node
      npm: 6.8.0 - ~/Downloads/node-v10.15.1-linux-x64/bin/npm
    npmPackages:
      react-native: github:status-im/react-native-desktop => 0.57.8 


```

If I simply remove BackAndroid.js, the error beings to happen in other files:

```
Loading dependency graph...(node:13529) UnhandledPromiseRejectionWarning: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: NetInfo
  Paths: /home/lz/orwell/orwellJS/node_modules/react-native/Libraries/Network/NetInfo.js collides with /home/lz/orwell/orwellJS/node_modules/react-native/Libraries/Network/NetInfo.desktop.js

```
In order to reproduce this bug you should just create a new app and do `npm install` then `npm start`

**Comment by lucaszanella** [comment]
I've found this: https://github.com/janeasystems/nodejs-mobile-react-native/tree/ed727edea17e8a9e1a85cef3413becc83b8a0328#duplicate-module-name but it needs adaptation for react-native-desktop.

Does somebone knows whats happening?

**Comment by vkjr** [comment]
That was fixed yesterday, please recreate the app or remove node_modules and install them again.

**Comment by lucaszanella** [comment]
I've been deleting node_modules and installing it again for hours. Gonna wait some hours more then, to see if it works

**Comment by vkjr** [comment]
Maybe npm ises cached version of react-native. Clean its cache to make sure it installs latest react-native-desktop.

**Comment by lucaszanella** [comment]
I think it takes time for npm to update because I've cleaned the cache several times, tried creating a new app and it won't work. I think the solution is to wait

**Comment by vkjr** [comment]
Did you run `react-native desktop` inside the freshly created project?

**Comment by lucaszanella** [comment]
yes, before npm install and npm start

**Comment by lucaszanella** [comment]
I'm still having this problem, even after doing
```
rm -rf node_modules/
rm -rf ~/.npm
npm cache clean --force
npm install
npm start
```

are you sure the npm module got updated?

**Comment by vkjr** [comment]
I had similar problem with npm, have no idea what causes it. In a test project I shared with you I used yarn and it did work well.

**Comment by lucaszanella** [comment]
Even 

```
yarn install
yarn start
```

gives the same problem

**Comment by lucaszanella** [comment]
```
 rm -rf node_modules/
 yarn cache clean
 yarn install
 yarn upgrade
```
seeing that yarn.lock points to the latest commit: 

```
"react-native@github:status-im/react-native-desktop":
  version "0.57.8"
  resolved "https://codeload.github.com/status-im/react-native-desktop/tar.gz/c122a2fa13bbd0039f06d0703d33e34084d96d66"

```

doing `yarn start`

also gives the error :(

**Comment by lucaszanella** [comment]
But for some reason recreating the app with yarn worked. Thank you for yur support :)

**Comment by lucaszanella** [comment]
I'm still having this error after months

**Comment by lucaszanella** [comment]
I've discovered how to reproduce this bug:

```
npm install -g react-native-cli 
react-native init DesktopSampleApp --version status-im/react-native-desktop
cd DesktopSampleApp
react-native desktop
npm start
```

it works, but if we do

```
rm -rf node_modules
yarn install
npm start #or yarn start
```

the error still happens

**Comment by lucaszanella** [comment]
Can this issue be opened again? It'll always happens to new apps

**Comment by madhavarshney** [comment]
This issue should be fixed by running `react-native desktop`.
