### ISSUE TITLE
An error message saying "We are not able to decrypt your data"

### ISSUE THREAD

**Issue by jinhojang6** [status-im/react-native-desktop#460]
## Environment
MacOS Mojave Version 10.14.3

## Description
I cannot access the desktop client all of a sudden with this error message.

<img width="1024" alt="screen shot 2019-03-05 at 12 11 42 pm" src="https://user-images.githubusercontent.com/41753422/53778411-f0fb4780-3f3f-11e9-992b-cb1eadb32495.png">

Also tried to delete and re-download the client but still does not work.

## Reproducible Demo
I didn't change anything and got this problem out of nowhere so cannot reproduce this bug.

**Comment by vkjr** [comment]
@jinhojang93, Please, remove all the data in `~/Library/Application Support/Status` directory and run the app again.
You will have to recover your account using seed word.

**Comment by jinhojang6** [comment]
> @jinhojang93, Please, remove all the data in `~/Library/Application Support/Status` directory and run the app again.
> You will have to recover your account using seed word.

@vkjr Thank you for the guide. But I cannot find the Status directory.

<img width="650" alt="screen shot 2019-03-05 at 10 24 59 pm" src="https://user-images.githubusercontent.com/41753422/53808510-c50ab100-3f95-11e9-9697-666748f34315.png">

**Comment by vkjr** [comment]
@jinhojang6, hm... I don't know other solution to this problem(

p.s. this is a `react-native-desktop` repo which is not really about `status-react` issues. So I'll close this one ;)
