### ISSUE TITLE
How can I interact with a renderable item?

### ISSUE THREAD

**Issue by lucaszanella** [status-im/react-native-desktop#476]
I tried to find a way but I couldn't.

If I implement an item in C++, how can I make it respond to queries sent by javascript?

In other words, how can I make my C++ item have callable properties from the javascript side? 

I discovered how to do it for non renderable c++ modules, but what about the renderabe ones?

**Comment by vkjr** [comment]
Did you try adding `Q_INVOKABLE` function to component manager?
Like this:
https://github.com/status-im/react-native-desktop/blob/master/ReactQt/runtime/src/componentmanagers/scrollviewmanager.h#L26

**Comment by lucaszanella** [comment]
So, let's say I implemented a C++ media player and in React Native I invoke it with

`<OrwellMediaPlayer uri={item.uri} width={640} height={360}/>`

How can I send a "pause" command to this media player?

I get that I can create `Q_INVOKABLE` methods in the C++ implementation, but how should I call them in javascript?

**Comment by vkjr** [comment]
Did you try using `ref` property?
