### ISSUE TITLE
Are there plans to upstream this?

### ISSUE THREAD

**Issue by ghost** [status-im/react-native-desktop#537]
I am just wondering, are there ever any plans to upstream this fork? Getting qt desktop support into react native would be good for maintainability. Has anyone contacted the react-native people about this?

**Comment by vkjr** [comment]
Hi!
No, there are no plans to upstream. `react-native-desktop` will be later separated in a package that installs along with `react-native` itself. There is no real need for it to be a part of `react-native`.
