### ISSUE TITLE
Is there a guide how to run react-native run-ubuntu/run-linux

### ISSUE THREAD

**Issue by tweakmy** [status-im/react-native-desktop#62]
Hi there,
I am struggling to find a proper documentation to actually build and run the tictactoe application on my ubuntu machine. Is there any guide?

**Comment by MaxRis** [comment]
Hello @tweakmy ,
[This](https://github.com/status-im/react-native-linux/blob/react-native-qt/README-ubuntu.md) guide is still relevant.
You also can check [doc to build and run examples with Qt Creator IDE ](https://github.com/status-im/react-native-linux/blob/react-native-qt/Development-linux.md)

After you have installed node modules with `npm install` into your copy of react-native-linux , currently it's required manually tweak the code in file node_modules/metro-bundler/src/defaults.js to add `ubuntu` platform. ( Please reference patch file there https://github.com/status-im/react-native-linux/blob/react-native-qt/add-ubuntu-platform.patch )

To build react-native-Linux and examples you can install and use latest Qt 5.9.1 from their official ftp https://download.qt.io/official_releases/qt/5.9/5.9.1/qt-opensource-linux-x64-5.9.1.run
Thanks

**Comment by tweakmy** [comment]
I got the following error:

>$ new/react-native-linux-build/Examples/TicTacToe# ./run-example.sh 
> QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
> -- Server starting
> ReactSourceCode::loadSource(QNetworkAccessManager*)::<lambda()> : Error while loading source "Connection refused"
> qml: redbox message: Failed to load source code

No idea what is the problem?

**Comment by MaxRis** [comment]
Hi @tweakmy ,

It should be related to the metro-bundler packager ... you should start it in advance before running TicTacToe sample application. To start it, open terminal with working directory at root of react-native-Linux clone and make sure following is done:
1. Run in terminal `npm install` to install node packages
2. Modify manually metro-bundler package code by adding `ubuntu` platform as I've described above
3. Run bundler process by terminal command `npm start`. Please left this terminal open in background.
4. Start TicTacToe sample app

After start of TicTacToe sample app, if you check terminal with running metro-bundler, you should see that TicTacToe bundle was requested (also composing of bundle for first time will take some time, approx. ~ 30 seconds, so TicTacToe app will load with this delay)

**Comment by vkjr** [comment]
@tweakmy, documentation was updated with more info on how to start the project - https://github.com/status-im/react-native-desktop#getting-started
If you'll face any problems please open a new issue. We will help with solving and update docs accordingly.
Closing this one for now.
